#!/bin/bash

docker network create rebase

docker run \
  --network rebase \
  --rm \
  --name ruby_server_rebase \
  -w /app \
  -v $(pwd):/app \
  -v gems:/usr/local/bundle/ \
  -p 3000:3000 \
  ruby \
  bash -c "bundle install && rackup server.rb -p 3000 -o 0.0.0.0"
