development:
  username: postgres
  port: 5432
  database: medical_records
  host: "postgres_db"
  password: password

test:
  username: postgres
  port: 5432
  database: medical_records_test
  host: "postgres_db"
  password: password
